### ISSUE TITLE
Need a peertube server book, so I can switch between different servers

### ISSUE THREAD

**Issue by lishoujun** [sschueller/peertube-android#70] opened 2018-12-29 15:57 UTC
Now there can only put one link.
I need a peertube server book, so I can switch between different servers.

**Comment by andy5995** [comment] 2019-02-11 09:22
Isn't this a duplicate of #1?

**Comment by andy5995** [comment] 2019-04-07 19:02
@sschueller this was implemented and can be closed, right?

**Comment by sschueller** [comment] 2019-04-08 07:10
@andy5995 the list is implemented however I also wanted to add a way to be able to switch and have credentials attached to servers.

**Closed** 2020-06-28 20:05 UTC
Labels: enhancement
